name: CI

on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v1
    with:
      version-file: '.tool-versions'
      enable-ct: true
      enable-audit: true
      enable-coverage: true
      enable-sbom: true
      enable-sbom-scan: true
      enable-dependency-submission: true
      enable-summary: true
      enable-mutate: true
      mutate-diff: true
      postgres: true
      postgres-db: 'test_db'
      postgres-password: 'postgres'
      kafka: true
