name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v1
    with:
      enable-eunit: false
      enable-fmt: false
      enable-xref: false
      enable-dialyzer: false
